# LINES = const(6)

KEYBOARD_DEBOUNCE_TIME_MS = const(150)

DISPLAY_WIDTH = const(128)
DISPLAY_HEIGHT = const(64)

CHAR_HEIGHT = const(8)
CHAR_WIDTH = const(5)

CHAR_PER_LINE = const(DISPLAY_WIDTH // CHAR_WIDTH)
